### ISSUE TITLE
Can't build executables

### ISSUE THREAD

**Issue by jacereda** [ndmitchell/ghc-make#11]
With:

```
e:\ghc-make>ghc --version
ghc --version
The Glorious Glasgow Haskell Compilation System, version 8.8.1

e:\ghc-make>cabal --version
cabal --version
cabal-install version 3.0.0.0
compiled using version 3.0.0.0 of the Cabal library 
```

Executing 

```
cabal install alex --with-ghc=ghc-make
```

Yields:

```
Command line: ghc -M -include-pkg-deps -dep-suffix= "" -dep-makefile dist/build/alex/alex-tmp/.ghc-make.makefile -fbuilding-cabal-package -O -static -outputdir dist\build\alex\alex-tmp -odir dist\build\alex\alex-tmp -hidir dist\build\alex\alex-tmp -stubdir dist\build\alex\alex-tmp -i -idist\build\alex\alex-tmp -isrc -idist\build\alex\autogen -idist\build\global-autogen -Idist\build\alex\autogen -Idist\build\global-autogen -Idist\build\alex\alex-tmp -optP-include -optPdist\build\alex\autogen\cabal_macros.h -hide-all-packages -Wmissing-home-modules -no-user-package-db -package-db C:\Users\jacereda\AppData\Roaming\cabal\store\ghc-8.8.1\package.db -package-db dist\package.conf.inplace -package-id array-0.5.4.0 -package-id base-4.13.0.0 -package-id containers-0.6.2.1 -package-id directory-1.3.3.2 -XHaskell98 -XCPP AbsSyn CharSet DFA DFAMin DFS Info Map NFA Output Paths_alex Parser ParseMonad Scan Set Sort Util UTF8 Data.Ranged Data.Ranged.Boundaries Data.Ranged.RangedSet Data.Ranged.Ranges src\Main.hs -o dist\build\alex\alex.exe -Wall -rtsopts -hide-all-packages -odir. -hidir. -hisuf=hi -osuf=o
Exit code: 1
Stderr:
ghc: can't apply -o to multiple source files
```

This happens after patching locally to add `--print-global-package-db` to the list of flags conflicting with `-M`.

I'm quite sure I'm misunderstanding something...

**Comment by ndmitchell** [comment]
I am kind of surprised to find anyone is still using this - or are you just trying to start? These kind of things are super fickle to keep working across cabal/ghc versions, so I had assumed it broke ages ago. If it's trivial to patch I'd take a PR... Could be a regression in `ghc -M`, or maybe the files used to be passed by filename but are now by module name? I think the `-o` here seems OK, but removing the `-o` and following argument is probably not harmful?

**Comment by jacereda** [comment]
I was just looking for some way to speed up the cabal build step for my build system and thought this could be the answer. Do you know of any other alternative nowadays to take advantage of all my idle cores?

**Comment by ndmitchell** [comment]
I think probably the best thing will be Buck2 - https://developers.facebook.com/blog/post/2021/07/01/future-of-buck/ - it should have worker tools (so the time to compile each file is low), parallelism and remote caching. It could be about 2x faster than ghc-make was. Hopefully will be open sourced within 6 months.

**Comment by jacereda** [comment]
Thanks, I'll keep an eye on that.

**Comment by ndmitchell** [comment]
I've added a note to this repo so people who come here in future are less likely to be surprised if it doesn't work.
